---
- name: Downloads dotfiles to temp directory
  git:
    repo: https://github.com/AJCandfield/dotfiles.git
    dest: "/tmp/dotfile"
    single_branch: true
    version: main

- name: Move files to user's home directory
  copy:
    remote_src: yes
    src: "/tmp/dotfile/"
    dest: "~{{ target_user }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  # when: not lookup('env', 'CI')
