---
extra_packages:
  - name: hstr
    repo: ppa:ultradvorka/ppa
    filename: hstr

  - name: python3.10
    repo: ppa:deadsnakes/ppa
    filename: python3

packages:
  - software-properties-common
  - curl
  - wget
  - zip
  - unzip
  - gzip
  - neovim
  - neofetch
  - htop
  - tmux
  - speedtest-cli
  - tree
  - flameshot

pip_packages:
  - pip
  - ansible
  - ansible-lint
  - yamllint
  - boto3
  - virtualenv
  - requests
  - pre-commit
