---
remove_packages:
  - name: snapd
  - name: gnome-user-docs
  - name: gnome-getting-started-docs
  - name: gnome-accessibility-themes
  - name: orca

extra_packages:
  - name: hstr
    repo: ppa:ultradvorka/ppa
    filename: hstr

  - name: python3.10
    repo: ppa:deadsnakes/ppa
    filename: python3

  - name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker

  - name:
      - terraform
      - packer
    repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp

  - name: kubectl
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

packages:
  - software-properties-common
  - jq
  - nodejs
  - npm
  - locate
  - curl
  - synaptic
  - wget
  - zip
  - unzip
  - gzip
  - neovim
  - neofetch
  - htop
  - tmux
  - speedtest-cli
  - tree
  - flameshot
  - nmap
  - fzf
  - direnv
  - gnome-shell-extensions-gpaste
  - gpaste
  - zsh
  - pass
  - ca-certificates
  - gnupg
  - lsb-release
  - inxi
  - fonts-powerline
  - zsh-syntax-highlighting
  - xfce4-terminal
  - hydra

npm_packages:
  - vtop

pip_packages:
  - pip
  - ansible
  - ansible-lint
  - yamllint
  - boto3
  - virtualenv
  - requests
  - pre-commit

dir_vim_plug: .local/share/nvim/site/autoload
