---
- name: Add repository for python
  apt_repository:
    repo: ppa:deadsnakes/ppa
    filename: python3

- name: Installs dependencies for python
  package:
    name: software-properties-common
    state: present

- name: Installs python
  package:
    name: "{{ python_version }}"
    state: present

- name: Stat python binary
  stat:
    path: "/usr/bin/{{ python_version }}"
  register: python_check

- name: Checking if python binary exists...
  assert:
    that: python_check.stat.exists
    success_msg: "{{ python_version }} successfully installed."
    fail_msg: "{{ python_version }} not found in /usr/bin folder."
