---
- name: Get latest aws-vault release version
  uri:
    url: https://api.github.com/repos/mozilla/sops/releases/latest
    body_format: json
    return_content: true
  register: aws_vault_version

- name: Deriving file name
  set_fact:
    aws_vault_package: "sops-{{ aws_vault_version.tag_name }}.linux"

- name: Download aws-vault
  get_url:
    url: "https://github.com/mozilla/sops/releases/latest/download/{{ aws_vault_package }}"
    dest: "~{{ user }}/.local/bin/sops"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
