---
- name: Copies files to temp directory
  git:
    repo: https://github.com/AJCandfield/dotfiles.git
    dest: "/tmp/dotfile"
    single_branch: true
    version: main

- name: Check if user exists
  getent:
    database: passwd
    key: "{{ user }}"

- name: Assert user exists
  assert:
    that: user in ansible_facts.getent_passwd
    success_msg: "User {{ user }} found. Installation can proceed."
    fail_msg: "User {{ user }} not found. Installation will soon stop."

- name: Move files to user's home directory
  copy:
    remote_src: yes
    src: "/tmp/dotfile/"
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Listing files in home directory
  shell: "ls -la ~{{ user | quote }}" # noqa 305
  changed_when: false
