---
- name: Copies files to home directory
  git:
    repo: https://github.com/AJCandfield/dotfiles.git
    dest: "/tmp/dotfile"
    single_branch: true
    version: master

- name: Move files to user's home directory
  copy:
    remote_src: yes
    src: "/tmp/dotfile/*"
    dest: "~{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Listing files in home directory
  shell: "ls -la ~{{ user | quote }}" # noqa 305
  changed_when: false
