---
- name: Add repository for python
  apt_repository:
    repo: ppa:deadsnakes/ppa
    filename: python3

- name: Installs dependencies for python
  package:
    name: software-properties-common
    state: present

- name: Installs latest python version
  package:
    name: python3.10
    state: present

- name: Running some check commands...
  shell: ls /usr/bin/python*
  register: python_check
  changed_when: false

- name: Check correct python version
  assert:
    that: "'python3.10' in {{ python_check.stdout }}"
    success_msg: Python3.10 successfully installed.
    fail_msg: Python3.10 not found in /usr/bin folder.

- name: Printing Python version...
  debug:
    var: python_check.stdout
