---
- name: Install zsh
  apt:
    package: zsh

- name: Check if oh-my-zsh exists
  stat:
    path: "~{{ user }}/.oh-my-zsh"
  register: omz

- name: Execute shell installation script
  become: true
  become_user: "{{ user }}"
  shell:
    chdir: /tmp
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: install.sh
  when: not omz.stat.exists

- name: Set user's shell to zsh
  user:
    name: "{{ user }}"
    shell: "/usr/bin/zsh"
