---
- name: Makes sure the main user exists
  user:
    name: "{{ user }}"
    comment: Alexander James Candfield

- name: Create general directories
  file:
    path: "~{{ user }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
  loop:
    - ".local/bin"
