---
- name: Add GPG key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

- name: Add GPG key for Hashicorp
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Add GPG key for Google
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
