---
- name: Add GPG key for Docker
  vars:
    keys:
      - url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

      - url: https://apt.releases.hashicorp.com/gpg

      - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

  apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.keyring | default(omit) }}"
  loop: "{{ keys }}"
