---
- name: Makes sure the target user exists
  user:
    name: "{{ target_user }}"
    groups: sudo
    append: true
    comment: Alexander James Candfield

- name: Creates home directories
  file:
    path: "~{{ target_user }}/{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    state: directory
    mode: 0755
  loop:
    - ".local/bin"

- name: Set user's shell to zsh
  user:
    name: "{{ target_user }}"
    shell: "/usr/bin/zsh"
