---
# https://askubuntu.com/a/597414
- name: Keybinding configuration
  block:
    - name: Check if print button key binding is already set
      command: gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings
      changed_when: false
      check_mode: false
      register: print_bind

    - name: Setup print button with flameshot
      when: "'flameshot' not in print_bind.stdout"
      command: "{{ item }}"
      loop:
        - gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '[]'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ name 'Flameshot'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ command '/usr/bin/flameshot gui'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ binding 'Print'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/']"
