---
- name: Adds extra repositories
  become: true
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: true
    filename: "{{ item.filename }}"
  loop: "{{ extra_packages }}"

- name: Installs extra packages
  become: true
  apt:
    package: "{{ item.name }}"
  loop: "{{ extra_packages }}"
  when: item.name is defined
