---
- name: Create vim-plug folder
  file:
    path: "~{{ target_user }}/{{ dir_vim_plug }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0644"

- name: Downloads vim-plug file
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~{{ target_user }}/{{ dir_vim_plug }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
