---
- name: Check if aws-cli already exists
  shell: "aws --version" # noqa 305
  become: true
  register: aws_cli
  changed_when: false
  check_mode: false
  failed_when: aws_cli.rc != 0 and aws_cli.rc != 127

- name: Installation of aws-cli
  become: true
  when: "'not found' in aws_cli.stderr"
  block:
    - name: Download aws-cli
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip archive
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp

    - name: Run installation script
      shell:
        cmd: /tmp/aws/install # noqa 305
        creates: /usr/local/bin/aws
      check_mode: false
