---
- name: Adds extra repositories
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: true
    filename: "{{ item.filename }}"
  loop: "{{ extra_packages }}"

- name: Installs extra packages
  apt:
    package: "{{ item.name }}"
  loop: "{{ extra_packages }}"
  when: item.name is defined

- name: Installs pip packages
  pip:
    name: "{{ pip_packages }}"
    executable: pip3

- name: Install NPM packages
  npm:
    name: "{{ item }}"
  loop: "{{ npm_packages }}"
