---
# tasks file for roles/system-update
- name: Importing other tasks...
  loop:
    - create_home
    - install_base_packages
    - install_extra_packages
    - install_pip_packages
    - config_keybindings
  include_tasks: "{{ item }}.yml"
