---
- become: true
  block:
    - include_tasks: config_user.yml

- become: true
  block:
    - include_tasks: remove_packages.yml

- become: true
  block:
    - include_tasks: add_gpg.yml

- become: true
  block:
    - include_tasks: install_base_packages.yml

- become: true
  block:
    - include_tasks: install_extra_packages.yml

- become: true
  block:
    - include_tasks: install_aws_cli.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_aws_vault.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_neovim.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_zsh.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_sops.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_dive.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_buildkit.yml
  tags: buildkit

- become: true
  block:
    - include_tasks: install_zoom.yml
  when: not is_ci # Skip this when executing on Github Actions

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_vscode.yml
  when: not is_ci # Skip this when executing on Github Actions

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: install_bitwarden.yml

- become: true
  block:
    - include_tasks: config_defaults.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: config_keybindings.yml
  when: not is_ci # Skip this when executing on Github Actions

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: config_locale.yml

- become: true
  become_user: "{{ target_user }}"
  block:
    - include_tasks: config_screen.yml
  when: not is_ci # Skip this when executing on Github Actions
