---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all

  pre_tasks:
    - name: Printing envars with Ansible
      debug:
        var: ansible_facts['env']

    - name: Setting some playbook variables
      set_fact:
        is_ci: "{{ lookup('env', 'CI') | bool | default('false') }}"

    - name: debug
      debug:
        var: is_ci
        verbosity: 1

  roles:
    - role: base

  post_tasks:
    - name: Installs dotfiles
      import_role:
        name: dotfiles
