---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: true

  pre_tasks:
    - name: Printing envars with Ansible
      debug:
        var: ansible_facts['env']

    - name: Setting some playbook variables
      set_fact:
        is_ci: lookup('env', 'CI') | default('false')

  roles:
    - role: base

    - role: home_dir

    - role: zsh

    - role: neovim

    - role: sops

    - role: aws_cli

    - role: aws_vault

    - role: vscode

    - role: zoom

  post_tasks:
    - name: Installs dotfiles
      import_role:
        name: dotfiles
