---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: true

  pre_tasks:
    - name: Printing envars with Ansible
      debug:
        var: ansible_facts['env']

  roles:
    - role: base

    - role: home_dir

    - role: python

    - role: zsh

    - role: neovim

    - role: sops

  post_tasks:
    - import_role:
        name: dotfiles
