---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: yes
  tasks:

    - name: Updates cache and upgrades system
      apt:
        update_cache: yes
        install_recommends: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Updates and upgrades system
      apt: # noqa 403
        package: "*"
        state: latest

    - name: Add repository for python
      apt_repository:
        repo: ppa:deadsnakes/ppa
        filename: python3

    - name: Installs dependencies for python
      package:
        name: software-properties-common
        state: present

    - name: Installs latest python version
      package:
        name: python3.10
        state: present

    - name: Running some check commands...
      shell: |
        which python
        which python3
        python -V
        python3 -V
      register: python_check
      changed_when: false

    - name: Printing Python version...
      debug:
        var: python_check
