---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: true
  vars:
    user: alex

  pre_tasks:
    - name: Printing envars with Ansible
      debug:
        var: ansible_facts['env']

    - name: Printing envars with shell
      shell: env # noqa 305
      changed_when: false

  roles:
    - role: base

    - role: home_dir

    - role: python

    - role: zsh

    - role: neovim
