---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: true
  roles:
    - role: setup_base
      vars:
        user: alex

    - role: setup_python

    - role: setup_zsh
      vars:
        user: alex
