---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: true
  pre_tasks:
    - name: Basic usage
      debug:
        var: lookup('env')
  roles:
    - role: base
      vars:
        user: alex

    - role: home_dir
      vars:
        user: alex

    - role: python

    - role: zsh
      vars:
        user: alex

    - role: neovim
      vars:
        user: alex
