---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: true

  pre_tasks:
    - name: Printing envars with Ansible
      debug:
        var: ansible_facts['env']

    - name: Printing envars with shell
      shell: env # noqa 305
      changed_when: false

  roles:
    - role: base
      vars:
        user: alex

    - role: home_dir
      vars:
        user: alex

    - role: python

    - role: zsh
      vars:
        user: alex

    - role: neovim
      vars:
        user: alex
