---
- name: This is the entry playbook which sets up your Ubuntu machine.
  hosts: all
  become: yes
  tasks:
    - name: Installs latest python version
      package:
        name: python3.10
        state: latest
