---
- name: Install neovim package
  apt:
    package: neovim

- name: Create vim-plug folder
  file:
    path: "~{{ user }}/{{ dir_vim_plug }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Downloads vim-plug file
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~{{ user }}/{{ dir_vim_plug }}"
    owner: "{{ user }}"
    group: "{{ user }}"
