---
name: Test Ansible on a Ubuntu 20.04 VM
on: ["push"]
jobs:
  run-playbook:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install ansible
      - uses: actions/checkout@v2
      - run: ansible-playbook playbooks/ping.yml
