---
name: Test Ansible on a Ubuntu 20.04 VM
on: ["push"]
jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Installing venv...
        run: python3 -m venv venv

      - name: Activating venv
        run: source venv/bin/activate ; which python

      - name: Installing pre-commit...
        run: pip install pre-commit

      - name: Installing Ansible...
        run: pip install ansible

      - name: Installing linting tools...
        run: pip install "ansible-lint" "yamllint"

      - name: Running pre-commits...
        run: pre-commit run -a

  run-playbook:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Installing venv...
        run: python3 -m venv venv

      - name: Activating venv
        run: source venv/bin/activate ; which python

      - name: Installing Ansible...
        run: pip install ansible

      - name: Running Ansible ping...
        run: ansible-playbook playbooks/ping.yml -vv

      - name: Running main Ansible playbook...
        run: ansible-playbook playbooks/setup-workstation.yml -vv

      - name: Listing packages...
        run: sudo apt list --installed
